// Actions for planetsReducer
export const REQUEST_PLANETS = 'REQUEST_PLANETS';
export const REQUEST_PLANETS_SUCCESS = 'REQUEST_PLANETS_SUCCESS';
export const REQUEST_PLANETS_FAILURE = 'REQUEST_PLANETS_FAILURE';
// Actions from filtersReducer
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_NUMERIC_VALUES = 'FILTER_BY_NUMERIC_VALUES';
export const DELETE_FILTER_BY_NUMERIC_VALUES = 'DELETE_FILTER_BY_NUMERIC_VALUES';
export const FILTER_BY_ORDER = 'FILTER_BY_ORDER';
